#Fri Oct 09 12:17:25 IST 2015
Hook.Failed.server= A repository hook failed
Hook.Failed.veb=Internal error occurred in server while completing the operation Please contact server admin to solve the issue
Checkin.Failed.Internal.Error.server=Checkin Failed due to internal server error.Please try again
Checkin.Failed.Internal.Error.veb=Check-in operation failed due to internal error. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
File.not.found.server=File not found
File.not.found.veb= File not found in Source control. Sourcesafe
Folder.or.cif.file.deletion.not.allowed.server=Request for folder or cif file deletion cannot be allowed from VeB
Folder.or.cif.file.deletion.not.allowed.veb=Operation forbidden: Folder or cif file cannot be deleted from VeB
Action.cannot.be.performed.server= Action cannot be performed due to internal network problem. Please try again
Action.cannot.be.performed.veb=Delete operation failed due to internal error. Please retry to complete the delete operation.
UnAuthorized.User.No.privilege.to.checkin.server=UnAuthorized User.User doesn't have privilege to checkin the files
UnAuthorized.User.No.privilege.to.checkin.veb=Access denied: User doesn't have privilege to perform this operation
Malformed.network.data.server=Malformed network data
Malformed.network.data.veb=Error occurred while transmitting data over the network. This error might occur due to  firewall or antivirus in system, Please disable  firewall or antivirus in your system and try again
VeB.file.contains.private.components.server=VeB file contains private components referring to other projects
VeB.file.contains.private.components.veb=Label operation cannot be performed as the VeB file contains private components referring to other projects
URL.access.forbidden.server=URL access forbidden for unknown reason
URL.access.forbidden.veb= Access  forbidden
Command.attempt.in.admin.dir.server=Attempted command in administrative dir
Command.attempt.in.admin.dir.veb=Accesss denied : Access to the specific item is not allowed
Obstructed.update.server=Obstructed update
Obstructed.update.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Bad.URL.server= Bad URL passed to RA layer
Bad.URL.veb=Unable to connect to the repository; Please check the URL for server and try to connect again
Delete.not.allowed.Public.Label.is.present.server=Delete cannot be allowed as requested file/folder has Public Label.
Delete.not.allowed.Public.Label.is.present.veb=Unable to perform operation. The requested file/folder has Public label
Label.applied.Unable.to.delete.server=Label is applied therefore unable to delete. Please contact server administrator for further details
Label.applied.Unable.to.delete.veb=Delete operation blocked as the file/folder being deleted has Label
Transaction.out.of.date.server=Transaction is out of date
Transaction.out.of.date.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Path.not.working.copy.server=Path is not a working copy
Path.not.working.copy.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Time.limit.exceeded.server=Time limit exceeds specified limit. Please contact server administrator for further details
Time.limit.exceeded.veb=Unable to perform the operation as time limit exceeded. Please try again later. If problem persist please contact server administrator to solve the issue
Connection.timed.out.server=Connection timed out
Connection.timed.out.veb=Connection to the server has been terminated. Please try again
Post.commit.hook.failed.server=Error running post-commit hook
Post.commit.hook.failed.veb=Internal error occurred in server while completing the operation Please contact server admin to solve the issue
Cannot.delete.Folder.has.sub.folders.server=Delete cannot be allowed as requested folder has sub folders in it
Cannot.delete.Folder.has.sub.folders.veb=Unable to perform operation. The requested file/folder has sub folders
Path.not.locked.server=Path is not locked
Path.not.locked.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
No.access.to.delete.server=User don't have access to delete. Please contact server administrator for further details
No.access.to.delete.veb=User don't have permission to perform this operation; Please contact server administrator to solve the issue
Error.while.processing.information.server=Error occurred while processing the information. Please contact server administrator for further details
Error.while.processing.information.veb=Internal error occurred. Please contact server administrator to solve the issue
Entry.has.no.URL.server= Entry has no URL
Entry.has.no.URL.veb=The specified path is incorrect. Check the source control path and try again
Invalid.operation.server=Invalid operation on the current working directory
Invalid.operation.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Revision.range.not.allowed.server=Revision range is not allowed
Revision.range.not.allowed.veb=Internal error occurred. The revision specified is not allowed
Bogus.Information.server=Bogus revision information given
Bogus.Information.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Label.already.in.use.server=Label is already used, so cannot apply the same label again
Label.already.in.use.veb=The specified label is already present. Please provide a different label to proceed with this operation
Post.lock.hook.Error.server=Error running post-lock hook
Post.lock.hook.Error.veb=Internal error occurred in server while completing the operation Please contact server admin to solve the issue
Unable.to.lock.file.server=Unable to lock the file
Unable.to.lock.file.veb=Unable to perform operation. File is already locked by \u201Cusername\u201D 
Repository.access.needed.server=Repository access is needed for this operation
Repository.access.needed.veb=Access denied: No access to the repository to perform this operation
Unexpected.property.server=Unexpected or unknown property kind
Unexpected.property.veb=Internal error occurred while performing this operation. Property <name> not found or unexpected
Filesystem.has.no.item.server=Filesystem has no item
Filesystem.has.no.item.veb=File or project not found in Source Control
Checkin.not.allowed.Contact.admin.server=Checkin cannot be allowed due to internal server error. Please contact server administrator for further details
Checkin.not.allowed.Contact.admin.veb=Check-in operation failed due to internal server error. Please contact server administrator to solve the issue 
Entry.already.exists.server=Entry already exists
Entry.already.exists.veb= File/ Folder already exist in Source control. Sourse safe
Bad.property.name.server=Bad property name
Bad.property.name.veb=Internal error occurred while performing this operation. Property <name> not found or unexpected
Network.connection.closed.server=Network connection closed unexpectedly
Network.connection.closed.veb=Network connection closed unexpectedly. Please check your network connection and retry again
Chargeable.component.included.server=Chargeable component has been included and must be removed in order to apply the label
Chargeable.component.included.veb=Label operation is not complete: Chargeable components are included. Please remove the component and try again.
Project.contains.INT.labeled.components.server=Public label cannot be applied, as the project contains one or more INT labeled components
Project.contains.INT.labeled.components.veb=Unable to apply Public label as the project contains one or more INT labeled components
Label.cannot.be.applied.Internal.Error.server=Label cannot be applied due to internal server error. Please contact server administrator for further details
Label.cannot.be.applied.Internal.Error.veb=Label Operation failed due to internal server error. Please contact administrator for further details.
Illegal.target.server=Illegal target for the requested operation
Illegal.target.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Dir.already.locked.server=Attempted to lock an already-locked dir
Dir.already.locked.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Relocation.not.allowed.server=Inter-repository relocation not allowed
Relocation.not.allowed.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Conflict.in.working.copy.server=A conflict in the working copy obstructs the current operation
Conflict.in.working.copy.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
No.such.entry.server=Filesystem directory has no such entry
No.such.entry.veb=File or Project doesn't exist. SourceSafe
Working.copy.is.corrupt.server=Working copy is corrupt
Working.copy.is.corrupt.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Item.not.readable.server=Item is not readable
Item.not.readable.veb=Accesss denied : Access to the specific item is not allowed
Risk.found.during.checkedin.server=Risk found in the files being checked-in. Checkin cannot be allowed
Risk.found.during.checkedin.veb=Checkin blocked as risk found in the files being checked-in
No.working.copy.path.server=Can't find a working copy path
No.working.copy.path.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Operation.not.complete.server=Previous operation has not finished; run 'cleanup' if it was interrupted
Operation.not.complete.veb=Internal error occurred. Please perform Source Control operation 'Clear connection data' and Connect again, after that proceed for your operation
Invalid.revision.number.server=Invalid filesystem revision number
Invalid.revision.number.veb=The Revision number is not present in SVN database
Authentication.failed.server=Authentication failed
Authentication.failed.veb=Access denied: Error occurred while authenticating. Please check with the administrator
Username.does.not.match.server=Username does not match lock owner
Username.does.not.match.veb=Unable to perform operation. File is already locked by \u201Cusername\u201D
RA.layer.request.failed.server=RA layer request failed
RA.layer.request.failed.veb=Unable to connect to the repository due to network issues
Delete.not.allowed.Time.exceeded.server=Delete cannot be allowed as time exceeds the limit
Delete.not.allowed.Time.exceeded.veb=Unable to perform operation. Time limit exceeded
Item.not.writable.server=Item is not writable
Item.not.writable.veb=Accesss denied : Write permission not available
Operation.forbidden.server=The operation is forbidden by the server
Operation.forbidden.veb=User don't have permission to perform this operation; its restricted by server
Delete.not.allowed.Internal.error.server=Delete cannot be allowed due to internal server error. Please contact server administrator for further details
Delete.not.allowed.Internal.error.veb=Delete operation failed due to internal server error. Please contact server administrator to solve the issue 
UnAuthorized.User.No.privilege.to.delete.server=UnAuthorized User. User doesn't have privilege to delete the file/folder
UnAuthorized.User.No.privilege.to.delete.veb=Access denied: User doesn't have privilege to perform this operation
RA.layer.file.already.exists.server=RA layer file already exists
RA.layer.file.already.exists.veb= File/ Folder already exist in Source control. Source safe
